### PR TITLE
[WIP] make /tmp a symlink in docker image

### PR DESCRIPTION
**Pull request by kkellerlbl**
Please do not merge yet, this is untested.

The genome annotation jobs write lots of output hardcoded to /tmp, which can fill the filesystem for nodes with a modest sized /var/lib/docker.  Rather than try to untangle what writes where, just try to symlink /tmp to /kb/module/work/tmp, so that the jobs write to the large scratch filesystem.

### CODE REVIEW

**Comment by kkellerlbl** [comment]
I looked in a running container, and confirmed that it is writing files to /tmp.  We probably haven't seen this issue because most of the temp files are small, or maybe because the genomes people have been submitting have been small.

**Comment by JamesJeffryes** [comment]
@kkellerlbl I'm trying to test this on Docker01 but it's using an old version of the docker file and failing to build. Can you rebase on the current master?

**Comment by kkellerlbl** [comment]
@JamesJeffryes did you mean that my fork was old?  If so, I've just merged all the changes in kbaseapps/RAST_SDK into my fork, so it should be up to date now.

**Review by JamesJeffryes — APPROVED** [review]
Tested in docker01. Looks good to me

**Pull request merged**
