### PR TITLE
Deactivating app in favor of new kb_plant_rast app

### PR DESCRIPTION
**Pull request by samseaver**

### CODE REVIEW

**Comment by JamesJeffryes** [comment]
@samseaver I think I'll hold off till we release the other annoatation app to merge this into master (just in case we have a bugfix to release here first) I'll also need you to bump the version number

**Comment by samseaver** [comment]
No problem, I'll update version when we're ready

**Comment by samseaver** [comment]
Has the other release happened yet?

**Comment by JamesJeffryes** [comment]
Probably not? I'm not familiar with who on the product team would need to
test it. On the implementation team, you would need someone more senior
than I to approve a new released module

**Review by JamesJeffryes — APPROVED** [review]
New app is released so this can be merged

**Pull request merged**
